CREATE TABLE "user" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "user_username" varchar NOT NULL,
  "user_role" varchar NOT NULL
);

CREATE TABLE "student" (
  "student_id" integer UNIQUE NOT NULL
);

CREATE TABLE "professor" (
  "professor_id" integer UNIQUE NOT NULL
);

CREATE TABLE "project" (
  "project_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "project_name" varchar NOT NULL,
  "project_code" varchar
);

CREATE TABLE "portfolio" (
  "portfolio_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "portfolio_studentId" integer NOT NULL,
  "portfolio_projectId" integer NOT NULL,
  "portfolio_name" varchar NOT NULL,
  "portfolio_content" varchar,
  "portfolio_visbility" varchar NOT NULL
);

CREATE TABLE "comment" (
  "comment_authorId" integer,
  "comment_portfolioId" integer,
  "comment_content" varchar NOT NULL
);

ALTER TABLE "student" ADD FOREIGN KEY ("student_id") REFERENCES "user" ("user_id");

ALTER TABLE "professor" ADD FOREIGN KEY ("professor_id") REFERENCES "user" ("user_id");

ALTER TABLE "portfolio" ADD FOREIGN KEY ("portfolio_studentId") REFERENCES "student" ("student_id");

ALTER TABLE "portfolio" ADD FOREIGN KEY ("portfolio_projectId") REFERENCES "project" ("project_id");

ALTER TABLE "comment" ADD FOREIGN KEY ("comment_authorId") REFERENCES "professor" ("professor_id");

ALTER TABLE "comment" ADD FOREIGN KEY ("comment_portfolioId") REFERENCES "portfolio" ("portfolio_id");

CREATE TABLE "project_user" (
  "project_project_id" integer,
  "user_user_id" integer,
  PRIMARY KEY ("project_project_id", "user_user_id")
);

ALTER TABLE "project_user" ADD FOREIGN KEY ("project_project_id") REFERENCES "project" ("project_id");

ALTER TABLE "project_user" ADD FOREIGN KEY ("user_user_id") REFERENCES "user" ("user_id");

